version: '3.8'

services:
  agent1:
    build: .
    container_name: azp-agent-linux-1
    environment:
      AZP_URL:        "https://dev.azure.com/AzDevOpsSampleOrg/"
      AZP_TOKEN:      "${AZP_TOKEN}"
      AZP_POOL:       "SelfHostedLinux"
      AZP_AGENT_NAME: "agent-linux-1"
      AZP_WORK:       "_work"
    volumes:
      - agent1_work:/azp/_work
    restart: unless-stopped

  agent2:
    build: .
    container_name: azp-agent-linux-2
    environment:
      AZP_URL:        "https://dev.azure.com/AzDevOpsSampleOrg/"
      AZP_TOKEN:      "${AZP_TOKEN}"
      AZP_POOL:       "SelfHostedLinux"
      AZP_AGENT_NAME: "agent-linux-2"
      AZP_WORK:       "_work"
    volumes:
      - agent2_work:/azp/_work
    restart: unless-stopped

volumes:
  agent1_work:
  agent2_work:
